apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: stefanprodan/podinfo
        name: hello
        env:
          - name: REGION
            valueFrom:
              configMapKeyRef:
                name: region
                key: name
