apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: simple-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: hello
  placement:
    clusterAffinity:
      clusterNames:
        - eu
        - ap
        - us
    replicaScheduling:
      replicaSchedulingType: Duplicated