apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: weighted-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: hello
  placement:
    clusterAffinity:
      clusterNames:
        - eu
        - ap
        - us
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - us
            weight: 4
          - targetCluster:
              clusterNames:
                - ap
            weight: 1
          - targetCluster:
              clusterNames:
                - eu
            weight: 1
